feat: Add `fastify` to `peerDependencies`
fastify/fastify-express pull request #101
Opened 2022-10-24 09:57 UTC by raon0211

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

`@fastify/express` is requiring `fastify` in the following line. 

https://github.com/fastify/fastify-express/blob/0e960f8ad3ea9be55c5c66091ba6ffcd97caae2e/index.js#L4

However, it does not specify `fastify` in neither `dependencies` nor `peerDependencies`, making the app break in stricter runtimes such as [Yarn PnP](https://yarnpkg.com/features/pnp). (See [packages should only ever require what they formally list in their dependencies](https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies))
```
Error: @fastify/express tried to access fastify, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: fastify (via "fastify/lib/symbols")
Required by: @fastify/express@npm:2.0.2 (via /.../node_modules/@fastify/express/)
```

I have fixed this behavior by adding `fastify` to `peerDependencies` in the package manifest.

2022-10-24 12:39 UTC, climba03003 commented
Always [long battle](https://github.com/fastify/fastify-swagger/issues/220#issuecomment-583280362) about `peerDependencies`

2022-10-24 12:44 UTC, climba03003 requested changes
Instead of `peerDependencies`, remove the usage of symbols.
Similar to https://github.com/fastify/middie/pull/142

2022-10-24 13:38 UTC, raon0211 commented
I just removed the symbols.

2022-10-24 15:20 UTC, climba03003 approved these changes

2022-10-24 15:51 UTC, SimenB commented
Should update PR title 🙂

2022-10-25 04:20 UTC, raon0211 commented
I have updated the title, thanks! 😄

2022-10-25 06:48 UTC, mcollina approved these changes
lgtm

2022-10-25 06:48 UTC, merged